"""Added column email to guests table

Revision ID: 758460e745ee
Revises: fe3a04208619
Create Date: 2025-11-20 13:38:17.265609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758460e745ee'
down_revision: Union[str, Sequence[str], None] = 'fe3a04208619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint('email', 'guests', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email', 'guests', type_='unique')
    op.drop_column('guests', 'email')
    # ### end Alembic commands ###
