"""renamed to guests table

Revision ID: c981bfbe1c61
Revises: e4f51de0f617
Create Date: 2025-11-20 13:43:09.275456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c981bfbe1c61'
down_revision: Union[str, Sequence[str], None] = 'e4f51de0f617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('guests', 'guests_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('guests_table', 'guests')
    # ### end Alembic commands ###
