"""Added column email_2 to guests table

Revision ID: e4f51de0f617
Revises: 758460e745ee
Create Date: 2025-11-20 13:42:12.210128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f51de0f617'
down_revision: Union[str, Sequence[str], None] = '758460e745ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('new_email', sa.String(length=255), nullable=False))
    op.drop_index(op.f('email'), table_name='guests')
    op.create_unique_constraint(op.f('uq_guests_email'), 'guests', ['email'])
    op.create_unique_constraint(op.f('uq_guests_new_email'), 'guests', ['new_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_guests_new_email'), 'guests', type_='unique')
    op.drop_constraint(op.f('uq_guests_email'), 'guests', type_='unique')
    op.create_index(op.f('email'), 'guests', ['email'], unique=True)
    op.drop_column('guests', 'new_email')
    # ### end Alembic commands ###
