"""Added columns first_name and last_name to guests table

Revision ID: fe3a04208619
Revises: 6ae56f0cfa4b
Create Date: 2025-11-20 13:34:41.221949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3a04208619'
down_revision: Union[str, Sequence[str], None] = '6ae56f0cfa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('guests', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'last_name')
    op.drop_column('guests', 'first_name')
    # ### end Alembic commands ###
